Add mieru plugin
MatsuriDayo/NekoBoxForAndroid pull request #482
Opened 2023-12-12 05:08 UTC by enfein

A testing NekoBoxForAndroid build can be found at https://github.com/enfein/NekoBoxForAndroid/actions/runs/7177103675

This patch requires installation of mieru plugin, which can be found at https://github.com/MatsuriDayo/plugins/pull/49

2024-01-04 00:56 UTC, enfein commented
@purofle

Can you help to review this patch? I built APKs with this patch, installed to my phone, and verified it is working.

Thank you

APK download: https://github.com/enfein/NekoBoxForAndroid/actions/runs/7403943262 and https://github.com/enfein/NekoBoxPlugins/actions/runs/7403962650

2024-01-09 16:30 UTC, purofle requested changes
在 `io.nekohasekai.sagernet.fmt.PluginEntry` 里添加下 Mieru，不然下载会炸

2024-01-10 05:34 UTC, enfein commented on app/src/main/java/io/nekohasekai/sagernet/ui/profile/MieruSettingsActivity.kt
> + * Copyright (C) 2021 by nekohasekai <contact-sagernet@sekai.icu>             *
这些有 copyright 的文件是从 SagerNet 项目复制过来的，例如这个文件是从 https://github.com/SagerNet/SagerNet/blob/dev/app/src/main/java/io/nekohasekai/sagernet/ui/profile/MieruSettingsActivity.kt 复制过来的。所以这些 copyright 不能删除。

2024-01-10 05:35 UTC, enfein commented on app/src/main/java/io/nekohasekai/sagernet/fmt/mieru/MieruFmt.kt
> +}
新的 commit 里面优化了嵌套的层数。

2024-01-10 05:35 UTC, enfein commented
> 在 `io.nekohasekai.sagernet.fmt.PluginEntry` 里添加下 Mieru，不然下载插件会炸

在新的 commit 里面解决了这个问题。

2024-01-10 14:50 UTC, purofle approved these changes

2024-01-10 14:50 UTC, merged

2024-08-25 09:19 UTC, alipornew1 approved these changes